import type { Quiz, QuizCategory, QuizStats } from "@/types/teacher/quiz.types";

export const MOCK_CATEGORIES: QuizCategory[] = [
  {
    id: "cat-math",
    name: "Mathematics",
    icon: "📐",
    quizCount: 8,
    totalStudents: 142,
    description: "Algebra, Geometry, Calculus",
    gradient: "from-violet-500 to-purple-700",
  },
  {
    id: "cat-science",
    name: "Science",
    icon: "🔬",
    quizCount: 12,
    totalStudents: 198,
    description: "Physics, Chemistry, Biology",
    gradient: "from-blue-500 to-cyan-600",
  },
  {
    id: "cat-english",
    name: "English",
    icon: "📖",
    quizCount: 6,
    totalStudents: 87,
    description: "Grammar, Vocabulary, Writing",
    gradient: "from-emerald-500 to-teal-600",
  },
  {
    id: "cat-history",
    name: "History",
    icon: "🏛️",
    quizCount: 5,
    totalStudents: 64,
    description: "World History, Events, Culture",
    gradient: "from-amber-500 to-orange-600",
  },
  {
    id: "cat-cs",
    name: "Computer Science",
    icon: "💻",
    quizCount: 10,
    totalStudents: 221,
    description: "Programming, Algorithms, Data",
    gradient: "from-indigo-500 to-blue-700",
  },
];

export const MOCK_QUIZZES: Quiz[] = [
  {
    id: "quiz-1",
    title: "Algebra Fundamentals",
    description: "Test your knowledge of basic algebraic expressions, equations, and inequalities. Covers linear equations, quadratic equations, and graphing.",
    categoryId: "cat-math",
    categoryName: "Mathematics",
    difficulty: "easy",
    status: "published",
    questionCount: 20,
    duration: 30,
    totalAttempts: 87,
    averageScore: 78,
    completionRate: 92,
    createdAt: "2026-03-15T09:00:00Z",
    updatedAt: "2026-04-10T14:30:00Z",
    tags: ["algebra", "equations", "basics"],
    emoji: "📐",
    gradient: "from-violet-500 to-purple-700",
  },
  {
    id: "quiz-2",
    title: "Cell Biology Basics",
    description: "Explore fundamental structures and functions of cells, including organelles, cell division, and membrane transport.",
    categoryId: "cat-science",
    categoryName: "Science",
    difficulty: "medium",
    status: "published",
    questionCount: 15,
    duration: 25,
    totalAttempts: 120,
    averageScore: 71,
    completionRate: 85,
    createdAt: "2026-03-20T10:00:00Z",
    updatedAt: "2026-04-12T11:00:00Z",
    tags: ["biology", "cells", "science"],
    emoji: "🔬",
    gradient: "from-blue-500 to-cyan-600",
  },
  {
    id: "quiz-3",
    title: "English Grammar Mastery",
    description: "A comprehensive quiz on English grammar rules, tenses, and sentence structure for intermediate learners.",
    categoryId: "cat-english",
    categoryName: "English",
    difficulty: "medium",
    status: "published",
    questionCount: 25,
    duration: 40,
    totalAttempts: 54,
    averageScore: 65,
    completionRate: 78,
    createdAt: "2026-02-28T08:00:00Z",
    updatedAt: "2026-04-05T09:00:00Z",
    tags: ["grammar", "english", "tenses"],
    emoji: "📖",
    gradient: "from-emerald-500 to-teal-600",
  },
  {
    id: "quiz-4",
    title: "World War II History",
    description: "Key events, battles, and figures of the Second World War covering 1939-1945.",
    categoryId: "cat-history",
    categoryName: "History",
    difficulty: "hard",
    status: "published",
    questionCount: 30,
    duration: 45,
    totalAttempts: 42,
    averageScore: 58,
    completionRate: 70,
    createdAt: "2026-01-15T07:00:00Z",
    updatedAt: "2026-03-28T16:00:00Z",
    tags: ["WWII", "history", "wars"],
    emoji: "🏛️",
    gradient: "from-amber-500 to-orange-600",
  },
  {
    id: "quiz-5",
    title: "Python Programming Basics",
    description: "Introduction to Python: variables, loops, functions, and data structures for beginners.",
    categoryId: "cat-cs",
    categoryName: "Computer Science",
    difficulty: "easy",
    status: "draft",
    questionCount: 18,
    duration: 35,
    totalAttempts: 0,
    averageScore: 0,
    completionRate: 0,
    createdAt: "2026-04-20T13:00:00Z",
    updatedAt: "2026-04-27T10:00:00Z",
    tags: ["python", "programming", "basics"],
    emoji: "💻",
    gradient: "from-indigo-500 to-blue-700",
  },
  {
    id: "quiz-6",
    title: "Advanced Calculus",
    description: "Derivatives, integrals, limits, and real-world applications of calculus for advanced students.",
    categoryId: "cat-math",
    categoryName: "Mathematics",
    difficulty: "hard",
    status: "published",
    questionCount: 22,
    duration: 50,
    totalAttempts: 38,
    averageScore: 52,
    completionRate: 61,
    createdAt: "2026-02-10T11:00:00Z",
    updatedAt: "2026-04-08T15:00:00Z",
    tags: ["calculus", "advanced", "math"],
    emoji: "∫",
    gradient: "from-violet-600 to-pink-600",
  },
  {
    id: "quiz-7",
    title: "Data Structures & Algorithms",
    description: "Arrays, linked lists, trees, graphs, sorting and searching algorithms.",
    categoryId: "cat-cs",
    categoryName: "Computer Science",
    difficulty: "hard",
    status: "archived",
    questionCount: 35,
    duration: 60,
    totalAttempts: 156,
    averageScore: 61,
    completionRate: 74,
    createdAt: "2025-12-01T09:00:00Z",
    updatedAt: "2026-03-01T12:00:00Z",
    tags: ["dsa", "algorithms", "cs"],
    emoji: "🌳",
    gradient: "from-slate-500 to-gray-600",
  },
  {
    id: "quiz-8",
    title: "Chemical Reactions",
    description: "Types of chemical reactions, balancing equations, and reaction rate concepts.",
    categoryId: "cat-science",
    categoryName: "Science",
    difficulty: "medium",
    status: "draft",
    questionCount: 16,
    duration: 28,
    totalAttempts: 0,
    averageScore: 0,
    completionRate: 0,
    createdAt: "2026-04-25T14:00:00Z",
    updatedAt: "2026-04-27T18:00:00Z",
    tags: ["chemistry", "reactions", "science"],
    emoji: "⚗️",
    gradient: "from-cyan-500 to-sky-600",
  },
];

const attempted = MOCK_QUIZZES.filter((q) => q.totalAttempts > 0);

export const MOCK_STATS: QuizStats = {
  totalQuizzes: MOCK_QUIZZES.length,
  publishedQuizzes: MOCK_QUIZZES.filter((q) => q.status === "published").length,
  draftQuizzes: MOCK_QUIZZES.filter((q) => q.status === "draft").length,
  archivedQuizzes: MOCK_QUIZZES.filter((q) => q.status === "archived").length,
  totalAttempts: MOCK_QUIZZES.reduce((s, q) => s + q.totalAttempts, 0),
  averageScore: Math.round(
    attempted.reduce((s, q) => s + q.averageScore, 0) / attempted.length
  ),
};
